[package]
name = "chacha20poly1305"
version = "0.2.2"
description = """
Pure Rust implementation of the ChaCha20Poly1305 Authenticated Encryption
with Additional Data Cipher (RFC 8439) with optional architecture-specific
hardware acceleration
"""
authors = ["RustCrypto Developers"]
edition = "2018"
license = "Apache-2.0 OR MIT"
readme = "README.md"
documentation = "https://docs.rs/chacha20poly1305"
repository = "https://github.com/RustCrypto/AEADs"
keywords = ["aead", "chacha20", "poly1305", "xchacha20", "xchacha20poly1305"]
categories = ["cryptography", "no-std"]

[badges]
maintenance = { status = "experimental" }

[dependencies]
aead = "0.2"
chacha20 = { version = "0.2.1", features = ["zeroize"] }
poly1305 = "0.5"
zeroize = { version = "1", default-features = false }

[features]
default = ["xchacha20poly1305"]
xchacha20poly1305 = ["chacha20/xchacha20"]
