language: rust
cache: cargo

rust:
  - stable
  - nightly

script:
  - cargo test --all --release --lib
  - cargo test --all --all-features --release

env:
  - RUSTFLAGS="-D warnings"

matrix:
  allow_failures:
    - name: rustfmt
    - name: clippy
    - rust: nightly
  fast_finish: true
  include:
    - name: "Rust: 1.37.0"
      rust: 1.37.0
      env: {} # clear `-D warnings` above; allow warnings
    - name: "Rust: stable (thumbv7em-none-eabihf)"
      rust: stable
      install: rustup target add thumbv7em-none-eabihf
      # TODO: test no_std builds of crypto_box when rust-lang/cargo#7916 is on stable
      script: cargo build --all --exclude ring-aead --exclude crypto_box --target thumbv7em-none-eabihf --release
    - name: rustfmt
      rust: stable
      install: rustup component add rustfmt
      script: cargo fmt --all -- --check
    - name: clippy
      rust: stable
      install:
        - rustup component add clippy
      script:
        - cargo clippy --all

branches:
  only:
    - master
