[workspace]
members = [
    "aes-gcm",
    "aes-gcm-siv",
    "aes-siv",
    "chacha20poly1305",
    "crypto_box",
    "ring-aead",
    "xsalsa20poly1305"
]

[patch.crates-io]
aes = { git = "https://github.com/RustCrypto/block-ciphers" }
aead = { git = "https://github.com/RustCrypto/traits" }
block-cipher = { git = "https://github.com/RustCrypto/traits" }
ghash = { git = "https://github.com/RustCrypto/universal-hashes" }
polyval = { git = "https://github.com/RustCrypto/universal-hashes" }
universal-hash = { git = "https://github.com/RustCrypto/traits" }
