[package]
name = "aes-siv"
version = "0.3.0-pre"
description = """
Pure Rust implementation of the AES-SIV Misuse-Resistant Authenticated
Encryption Cipher (RFC 5297) with optional architecture-specific
hardware acceleration
"""
authors = ["RustCrypto Developers"]
edition = "2018"
license = "Apache-2.0 OR MIT"
readme = "README.md"
documentation = "https://docs.rs/aes-siv"
repository = "https://github.com/RustCrypto/AEADs"
keywords = ["aead", "aes", "encryption", "siv"]
categories = ["cryptography", "no-std"]

[dependencies]
aead = { version = "= 0.3.0-pre", default-features = false }
aes = "= 0.4.0-pre"
cmac = "= 0.3.0-pre"
crypto-mac = { version = "= 0.8.0-pre", default-features = false }
ctr = "= 0.4.0-pre"
dbl = { version = "= 0.3.0-pre", default-features = false }
pmac = { version = "= 0.3.0-pre", optional = true }
stream-cipher = { version = "= 0.4.0-pre", default-features = false }
zeroize = { version = "1", default-features = false }

[dev-dependencies]
hex-literal = "0.2"

[features]
default = ["alloc"]
alloc = ["aead/alloc"]
heapless = ["aead/heapless"]

[package.metadata.docs.rs]
all-features = true
