[package]
name = "aes-siv"
version = "0.1.0"
authors = ["RustCrypto Developers"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "AES-SIV: Misuse-Resistant Authenticated Encryption Cipher (RFC 5297)"
readme = "README.md"
documentation = "https://docs.rs/aes-siv"
repository = "https://github.com/RustCrypto/AEADs"
keywords = ["aead", "aes", "encryption", "siv"]
categories = ["cryptography", "no-std"]

[badges]
maintenance = { status = "passively-maintained" }

[dependencies]
aead = "0.1"
aes = "0.3"
cmac = "0.2"
crypto-mac = { version = "0.7", default-features = false }
ctr = "0.3"
dbl = { version = "0.2", default-features = false }
pmac = { version = "0.2", optional = true }
stream-cipher = { version = "0.3", default-features = false }
zeroize = { version = "1.0.0-pre", default-features = false }

[dev-dependencies]
subtle-encoding = "0.3"
serde_json = "1"

[features]
default = ["alloc"]
alloc = []

[package.metadata.docs.rs]
all-features = true
