[package]
name = "aes-gcm"
version = "0.2.0"
description = """
Pure Rust implementation of the AES-GCM (Galois/Counter Mode)
Authenticated Encryption with Associated Data (AEAD) Cipher
with optional architecture-specific hardware acceleration
"""
authors = ["RustCrypto Developers"]
edition = "2018"
license = "Apache-2.0 OR MIT"
readme = "README.md"
documentation = "https://docs.rs/aes-gcm"
repository = "https://github.com/RustCrypto/AEADs"
keywords = ["aead", "aes", "encryption", "gcm", "ghash"]
categories = ["cryptography", "no-std"]

[badges]
maintenance = { status = "experimental" }

[dependencies]
aead = { version = "0.2", default-features = false }
aes = "0.3"
ghash = { version = "0.2.2", default-features = false }
subtle = { version = "2", default-features = false }
zeroize = { version = "1", default-features = false }

[dev-dependencies]
criterion = "0.3.0"
criterion-cycles-per-byte = "0.1.1"
hex-literal = "0.2"

[features]
default = ["alloc"]
alloc = ["aead/alloc"]

[[bench]]
name = "aes-gcm"
harness = false
