[package]
name = "aes-gcm-siv"
version = "0.1.0"
authors = ["RustCrypto Developers"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "AES-GCM-SIV: Misuse-Resistant Authenticated Encryption Cipher (RFC 8452)"
readme = "README.md"
documentation = "https://docs.rs/aes-gcm-siv"
repository = "https://github.com/RustCrypto/AEADs"
keywords = ["aead", "aes", "aes-gcm", "encryption", "siv"]
categories = ["cryptography", "no-std"]

[badges]
maintenance = { status = "experimental" }

[dependencies]
aead = "0.1"
aes = "0.3"
polyval = "0.3"
subtle = { version = "2", default-features = false }
zeroize = { version = "1.0.0-pre", default-features = false }

[dev-dependencies]
criterion = "0.3.0"
criterion-cycles-per-byte = "0.1.1"

[[bench]]
name = "aes-gcm-siv"
harness = false
